#!/bin/bash
# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.
# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo
# Command handling tests

echo "--------------------------------------------"
echo "----------- NON-INTERACTIVE MODE -----------"
echo "--------------------------------------------"
echo
echo "TEST: Regular \"ls #a message\""
echo "==========[sh]=========="
echo "pwd # ls -la " | sh
echo
echo "==========[hsh]========="
echo "pwd # ls -la" | ./hsh
echo
echo --------------------------------------------
echo "TEST: Trailing spaces \"date                     # pwd\""
echo "==========[sh]=========="
echo "date                     # pwd" | sh
echo
echo "==========[hsh]========="
echo "date                     # pwd" | ./hsh
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
